<?php

namespace OIF\PlatformBundle\Repository\CommissionCinema;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository{
    public function getCommssionCinema(){
        return $this
            ->createQueryBuilder('c')
            ->where('c.type = 2')
            ->andWhere('c.etat = 1')
            ;
    }
}
