## Page cinéma
oif_platform_cinema:
    path:     /commission-cinema
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:index }

oif_platform_cinema_view:
    path:     /commission-cinema/projet-{id}
    defaults:
        _controller: OIFPlatformBundle:CommissionCinema:view
    requirements:
        id: \d+

## Ajouter un projet cinéma
oif_platform_cinema_add:
    path:     /commission-cinema/add
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:add }

###### Ajouter un plan de financement au projet cinéma ######
oif_platform_cinema_addFinancement:
    path:     /commission-cinema/add-financement-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:addFinancement }
## Supprimer un financement au projet cinéma
oif_platform_cinema_deleteFinancement:
    path:     /commission-cinema/delete-financement-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:deleteFinancement }

###### Ajouter un lien au projet cinéma ######
oif_platform_cinema_addLien:
    path:     /commission-cinema/add-lien-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:addLien }
## Supprimer un lien au projet cinéma
oif_platform_cinema_deleteLien:
    path:     /commission-cinema/delete-lien-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:deleteLien }

###### Ajouter une piece au projet cinéma ######
oif_platform_cinema_addPiece:
    path:     /commission-cinema/add-piece-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:addPiece}
## Supprimer une piece du projet cinéma ######
oif_platform_cinema_deletePiece:
    path:     /commission-cinema/delete-piece-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:deletePiece }

# Modifier un projet cinéma ######
oif_platform_cinema_edit_fiche:
    path:     /commission-cinema/edit-fiche-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:editFiche }

oif_platform_cinema_edit_piece:
    path:     /commission-cinema/edit-piece-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:editPiece }


## Page cinéma
oif_platform_audiovisuelle:
    path:     /commission-audiovisuelle
    defaults: { _controller: OIFPlatformBundle:CommissionAudiovisuelle:index }

oif_platform_audiovisuelle_add:
    path:     /commission-audiovisuelle/add
    defaults: { _controller: OIFPlatformBundle:CommissionAudiovisuelle:add }

