## Page cinéma
oif_platform_cinema:
    path:     /commission-cinema
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:index }

oif_platform_cinema_view:
    path:     /commission-cinema/projet-{id}
    defaults:
        _controller: OIFPlatformBundle:CommissionCinema:view
    requirements:
        id: \d+

oif_platform_cinema_add:
    path:     /commission-cinema/add
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:add }

oif_platform_cinema_addFinancement:
    path:     /commission-cinema/add-financement-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:addFinancement }

oif_platform_cinema_edit_fiche:
    path:     /commission-cinema/edit-fiche-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:editFiche }

oif_platform_cinema_edit_piece:
    path:     /commission-cinema/edit-piece-{id}
    defaults: { _controller: OIFPlatformBundle:CommissionCinema:editPiece }


## Page cinéma
oif_platform_audiovisuelle:
    path:     /commission-audiovisuelle
    defaults: { _controller: OIFPlatformBundle:CommissionAudiovisuelle:index }

oif_platform_audiovisuelle_add:
    path:     /commission-audiovisuelle/add
    defaults: { _controller: OIFPlatformBundle:CommissionAudiovisuelle:add }

