services:
#    oif_platform.example:
#        class: OIF\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oif_platform.fichiers_documentaireserie:
        class: OIF\PlatformBundle\FiltreFichiers\FichiersDocumentaireSerie
    oif_platform.fichiers_cinema:
        class: OIF\PlatformBundle\FiltreFichiers\FichiersCinema
