<?php

namespace OIF\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends EntityRepository{

    public function getLikeQueryBuilder($pattern)
    {
        return $this
            ->createQueryBuilder('c')
            ->where('c.noPays != :pattern')
            ->setParameter('pattern', $pattern)
            ;
    }
}
