<?php

namespace OIF\PlatformBundle\Repository\CommissionDocumentaireSerie;

/**
 * FichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierRepository extends \Doctrine\ORM\EntityRepository
{
}
