<?php

namespace OIF\PlatformBundle\Repository\CommissionDocumentaireSerie;

/**
 * LienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienRepository extends \Doctrine\ORM\EntityRepository
{
}
